### PR TITLE
- Adjusted the source to work with the latest MCP Forge. There's a fe…

### PR DESCRIPTION
**Pull request by mossyblog**
Adjusted the source to work with the latest MCP Forge (Github). There appears to be name changes in the methods and some of the mappings haven't been deobsfucated either.

Maybe of some use? i just needed it to work with my local ver of Forge as-is. (Direct github pull + compile out of the box). I'm not sure of MDK changes the mappings back or unlocks some of the private/protected back to public either. It appears not the case.

### CODE REVIEW

**Comment by Lunatrius** [comment]
The mappings are already defined inside [gradle.properties](https://github.com/Lunatrius/Schematica/blob/master/gradle.properties#L7) and are used when the user cloning the repository runs `gradle setupDecompWorkspace idea / eclipse`.

It's worth noting that the current Forge uses [older mappings](https://github.com/MinecraftForge/MinecraftForge/blob/master/build.gradle#L25) than what Schematica currently uses.

**Comment by mossyblog** [comment]
Heya,

Ahh that explains it, this release is only currently targeted at the recommended and I was jumping ahead a bit with the Forge github repo's but realising now that their mappings are behind, specifically also i noticed that stable_16 also seems to bottom out when you try and run a build (MinecratfForge/build.gradle) 

This is all confusing ;) hehe.. it's like i want the "latest latest" but there appears to be some kind of shadow repo of some sorts elsewhere outside of github? ..as the moment i switch from snapshot_nodoc_20141130 to stable_16 no build passes.

**Comment by Lunatrius** [comment]
You shouldn't have to use the Forge source directly.

As for the crash. It's most likely because Schematica currently uses FG1.2 while the latest Forge uses FG2.0. If you still want to use it with the Forge sources directly I suggest you to checkout Forge 11.14.3.1450.

**Comment by mossyblog** [comment]
Yeah i was just trying to find out where that is, I mean MDK route is fine (Src is kind of there?), but i'm keen to also use the MinecraftForge github source as well as i like to know how it all glues together (especially given I'm trying to overlay textures onto existing blocks in a seperate layer - that - or do what you're doing and use virtual ghost blocks).

Basically finding ones feet in this is a bit tricky to begin with :)

**Pull request closed without merging**
