### PR TITLE
Schematica API

### PR DESCRIPTION
**Pull request by AtomicBlom**
provides events from Schematica that other mods can interact with.

### CODE REVIEW

**Comment by Lunatrius** [comment]
Talked with some other people a bit and it's apparently a good idea to have `package-info.java` in the sub-packages of the API as well. It may save some trouble later down the line.

And if you could revert the changes to `SchematicWorld`, most of those things will be going away after implementing ISchematic in the data class anyway.

**Comment by AtomicBlom** [comment]
Oh? Did they say what needs to go in the package-info? Does that need an API annotation as well?

**Comment by Lunatrius** [comment]
Yeah, it's the same thing essentially, except that the owner is the parent package. Best example is probably BuildCraft.

**Comment by AtomicBlom** [comment]
Cool, I'll go check how they did it then. In the meantime, SchematicWorld has been reverted

**Comment by Lunatrius** [comment]
https://github.com/BuildCraft/BuildCraft/blob/6.1.x/api/buildcraft/api/events/package-info.java

**Comment by AtomicBlom** [comment]
I'm wondering if I should make that DuplicateMappingException part of the events package. It's quite related to an operation you perform on an event.

**Comment by Lunatrius** [comment]
Sure thing. Was thinking about that as well, must've forgotten it.

**Comment by Lunatrius** [comment]
`SchematicaAPI` / `SchematicaAPI|events` maybe, instead of the current one?

**Comment by AtomicBlom** [comment]
Are those APIs what you had in mind?

**Comment by Lunatrius** [comment]
Yeah. The events didn't have "api" in the name before.

**Comment by AtomicBlom** [comment]
Do you know if the API tag "Owner" or "provider" reference anything? The example I saw from Minalien lead me to believe that the owner was the ModId?

**Comment by Lunatrius** [comment]
If I remember correctly the owner tag is there so that in case of multiple versions the one included with the mod is picked over any other versions.

**Comment by Lunatrius** [comment]
Anyway, if you want to squash, otherwise I can just pull it. Don't think there's anything left to do.

**Comment by AtomicBlom** [comment]
No worries, I'll squash it and pass it through

**Pull request merged**
